/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ExperimentsVariantsLazyImport = createFileRoute('/experiments/variants')()
const ExperimentsSdkLazyImport = createFileRoute('/experiments/sdk')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ExperimentsVariantsLazyRoute = ExperimentsVariantsLazyImport.update({
  path: '/experiments/variants',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/experiments/variants.lazy').then((d) => d.Route),
)

const ExperimentsSdkLazyRoute = ExperimentsSdkLazyImport.update({
  path: '/experiments/sdk',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/experiments/sdk.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/experiments/sdk': {
      preLoaderRoute: typeof ExperimentsSdkLazyImport
      parentRoute: typeof rootRoute
    }
    '/experiments/variants': {
      preLoaderRoute: typeof ExperimentsVariantsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  ExperimentsSdkLazyRoute,
  ExperimentsVariantsLazyRoute,
])

/* prettier-ignore-end */
